apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis_service_fullname" . }}
  labels:
    app: {{ template "redis_service_fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: redis
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - port: 6379
    targetPort: redis
  selector:
    app: {{ template "redis_fullname" . }}
